name: 'Release: My Product'
description: 'Release new version of my product at specific environment'

on:
  workflow_dispatch:
    inputs:
      # usage: ${{ github.event.inputs.environment }}
      environment:
        description: 'Environment to enroll new version: production or staging'
        options:
          - staging
          - production
        required: true
        default: staging
        type: choice
      version:
        description: 'Version of released my product'
        required: true
        type: string
        default: x.0

env:
  PRODUCT_VERSION: ${{ github.event.inputs.version }}
  PRODUCT_ENV: ${{ github.event.inputs.environment }}

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Is actor allowed
        shell: python
        run: |
          import json
          from os import environ
          from sys import exit

          actor = '${{ github.actor }}'
          var_key = 'ALLOWED_ACTORS'

          allowed_actors = json.loads(environ.get(var_key, '[]'))
          if actor not in allowed_actors:
            summary_path = environ['GITHUB_STEP_SUMMARY']
            with open(summary_path, 'a') as f:
              f.write(
                f'# Actor `{actor}` is not allowed to run workflow. '
                f'Check `{var_key}` variable in `Environments` settings\n'
              )
              exit(1)

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run release
        shell: bash
        run: set -e && ./run_release.sh

      - name: Generate summary
        shell: bash
        run: |
          printf '# Release\n' >> $GITHUB_STEP_SUMMARY
          printf '%s Applied to env: `%s`\n' '-' '${{ github.event.inputs.environment }}' >> $GITHUB_STEP_SUMMARY
          printf '%s Version: `%s`\n' '-' '${{ github.event.inputs.version }}' >> $GITHUB_STEP_SUMMARY
          printf '# GitHub\n' >> $GITHUB_STEP_SUMMARY
          printf '```\n' >> $GITHUB_STEP_SUMMARY
          printf '%s\n' '${{ toJson(github) }}' >> $GITHUB_STEP_SUMMARY
          printf '```\n' >> $GITHUB_STEP_SUMMARY
          printf '# Stored envs and secrets\n' >> $GITHUB_STEP_SUMMARY
          printf '%s Secrets:\n    ```%s\n' '-' '${{ secrets }}' >> $GITHUB_STEP_SUMMARY
          printf '    ```\n' >> $GITHUB_STEP_SUMMARY
          printf '\n' >> $GITHUB_STEP_SUMMARY
          printf '%s Envs:\n    ```%s\n' '-' '${{ vars }}' >> $GITHUB_STEP_SUMMARY
          printf '    ```\n' >> $GITHUB_STEP_SUMMARY
